name: Tryout

on: [push]

jobs:
  tryout:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Calculating and setting sha256sum
      id: sha256sum
      run: |
        echo "value=$(sha256sum LICENSE | cut -d ' ' -f1)" >> "$GITHUB_OUTPUT"

    - name: Getting sha256sum
      run: |
        echo "Got sha256sum: ${{steps.sha256sum.outputs.value}}"
